version: "3.8"
services:
  mongodb:
    image: "mongo:4.0"
    # networks:
      # - webapp
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - data:/data/db
  


  # backend:
    # image: "node"

  # frontend:
    # image: "node"

volumes:
  data: